events {}

http {
  upstream core_api  { server core-service:8080; }
  upstream study_api { server study-service:8080; }

  server {
    listen 80;

    client_max_body_size 50m;

    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_read_timeout 120s;
    proxy_send_timeout 120s;

    # normalize paths without trailing slash
    location = /api/core  { return 301 /api/core/; }
    location = /api/study { return 301 /api/study/; }

    # Core
    location /api/core/ {
      proxy_pass http://core_api/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Study
    location /api/study/ {
      proxy_pass http://study_api/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}